package net.rohlandm.aoc24.application

import org.scalatest.funsuite.AnyFunSuite

/**
 * Test cases for [[Day8Solver]]
 */
class Day8SolverTest extends AnyFunSuite:
  private val testInput =
    """............
      |........0...
      |.....0......
      |.......0....
      |....0.......
      |......A.....
      |............
      |............
      |........A...
      |.........A..
      |............
      |............
      |""".stripMargin.split("\n").toList


  test("solvePart1 returns result"):
    assert(Day8Solver().solvePart1(testInput) === Some(14))

  test("solvePart2 returns result"):
    assert(Day8Solver().solvePart2(testInput) === None)

